const appData = {
    hsk1: {
        vocabulary: [
            { id: "h1_1", hanzi: "我", pinyin: "wǒ", meaning: "tôi, tao, tớ", type: "pron" },
            { id: "h1_2", hanzi: "你", pinyin: "nǐ", meaning: "bạn, mày, cậu", type: "pron" },
            { id: "h1_3", hanzi: "他", pinyin: "tā", meaning: "anh ấy, ông ấy", type: "pron" },
            { id: "h1_4", hanzi: "她", pinyin: "tā", meaning: "cô ấy, bà ấy", type: "pron" },
            { id: "h1_5", hanzi: "我们", pinyin: "wǒmen", meaning: "chúng tôi", type: "pron" },
            { id: "h1_6", hanzi: "好", pinyin: "hǎo", meaning: "tốt, khỏe", type: "adj" },
            { id: "h1_7", hanzi: "是", pinyin: "shì", meaning: "là", type: "v" },
            { id: "h1_8", hanzi: "不", pinyin: "bù", meaning: "không", type: "adv" },
            { id: "h1_9", hanzi: "很", pinyin: "hěn", meaning: "rất", type: "adv" },
            { id: "h1_10", hanzi: "吃", pinyin: "chī", meaning: "ăn", type: "v" },
            { id: "h1_11", hanzi: "喝", pinyin: "hē", meaning: "uống", type: "v" },
            { id: "h1_12", hanzi: "去", pinyin: "qù", meaning: "đi", type: "v" },
            { id: "h1_13", hanzi: "来", pinyin: "lái", meaning: "đến", type: "v" },
            { id: "h1_14", hanzi: "看", pinyin: "kàn", meaning: "nhìn, xem", type: "v" },
            { id: "h1_15", hanzi: "听", pinyin: "tīng", meaning: "nghe", type: "v" },
            { id: "h1_16", hanzi: "有", pinyin: "yǒu", meaning: "có", type: "v" },
            { id: "h1_17", hanzi: "在", pinyin: "zài", meaning: "ở, đang", type: "prep" },
            { id: "h1_18", hanzi: "大", pinyin: "dà", meaning: "to, lớn", type: "adj" },
            { id: "h1_19", hanzi: "小", pinyin: "xiǎo", meaning: "nhỏ, bé", type: "adj" },
            { id: "h1_20", hanzi: "多", pinyin: "duō", meaning: "nhiều", type: "adj" },
            { id: "h1_21", hanzi: "少", pinyin: "shǎo", meaning: "ít", type: "adj" },
            { id: "h1_22", hanzi: "人", pinyin: "rén", meaning: "người", type: "n" },
            { id: "h1_23", hanzi: "名字", pinyin: "míngzi", meaning: "tên", type: "n" },
            { id: "h1_24", hanzi: "妈妈", pinyin: "māma", meaning: "mẹ", type: "n" },
            { id: "h1_25", hanzi: "爸爸", pinyin: "bàba", meaning: "bố", type: "n" },
            { id: "h1_26", hanzi: "猫", pinyin: "māo", meaning: "con mèo", type: "n" },
            { id: "h1_27", hanzi: "狗", pinyin: "gǒu", meaning: "con chó", type: "n" },
            { id: "h1_28", hanzi: "今天", pinyin: "jīntiān", meaning: "hôm nay", type: "n" },
            { id: "h1_29", hanzi: "明天", pinyin: "míngtiān", meaning: "ngày mai", type: "n" },
            { id: "h1_30", hanzi: "昨天", pinyin: "zuótiān", meaning: "hôm qua", type: "n" },
            { id: "h1_31", hanzi: "水", pinyin: "shuǐ", meaning: "nước", type: "n" },
            { id: "h1_32", hanzi: "茶", pinyin: "chá", meaning: "trà", type: "n" },
            { id: "h1_33", hanzi: "米饭", pinyin: "mǐfàn", meaning: "cơm", type: "n" },
            { id: "h1_34", hanzi: "苹果", pinyin: "píngguǒ", meaning: "quả táo", type: "n" },
            { id: "h1_35", hanzi: "喜欢", pinyin: "xǐhuan", meaning: "thích", type: "v" },
            { id: "h1_36", hanzi: "爱", pinyin: "ài", meaning: "yêu", type: "v" },
            { id: "h1_37", hanzi: "个", pinyin: "gè", meaning: "cái, con (lượng từ)", type: "m" },
            { id: "h1_38", hanzi: "岁", pinyin: "suì", meaning: "tuổi", type: "m" },
            { id: "h1_39", hanzi: "钱", pinyin: "qián", meaning: "tiền", type: "n" },
            { id: "h1_40", hanzi: "什么", pinyin: "shénme", meaning: "cái gì", type: "pron" },
            { id: "h1_41", hanzi: "零", pinyin: "líng", meaning: "số không", type: "num" },
            { id: "h1_42", hanzi: "一", pinyin: "yī", meaning: "một", type: "num" },
            { id: "h1_43", hanzi: "二", pinyin: "èr", meaning: "hai", type: "num" },
            { id: "h1_44", hanzi: "三", pinyin: "sān", meaning: "ba", type: "num" },
            { id: "h1_45", hanzi: "四", pinyin: "sì", meaning: "bốn", type: "num" },
            { id: "h1_46", hanzi: "五", pinyin: "wǔ", meaning: "năm", type: "num" },
            { id: "h1_47", hanzi: "六", pinyin: "liù", meaning: "sáu", type: "num" },
            { id: "h1_48", hanzi: "七", pinyin: "qī", meaning: "bảy", type: "num" },
            { id: "h1_49", hanzi: "八", pinyin: "bā", meaning: "tám", type: "num" },
            { id: "h1_50", hanzi: "九", pinyin: "jiǔ", meaning: "chín", type: "num" },
            { id: "h1_51", hanzi: "十", pinyin: "shí", meaning: "mười", type: "num" },
            { id: "h1_52", hanzi: "中国", pinyin: "Zhōngguó", meaning: "Trung Quốc", type: "n" },
            { id: "h1_53", hanzi: "北京", pinyin: "Běijīng", meaning: "Bắc Kinh", type: "n" },
            { id: "h1_54", hanzi: "老师", pinyin: "lǎoshī", meaning: "giáo viên", type: "n" },
            { id: "h1_55", hanzi: "学生", pinyin: "xuésheng", meaning: "học sinh", type: "n" },
            { id: "h1_56", hanzi: "医生", pinyin: "yīshēng", meaning: "bác sĩ", type: "n" },
            { id: "h1_57", hanzi: "朋友", pinyin: "péngyou", meaning: "bạn bè", type: "n" },
            { id: "h1_58", hanzi: "学校", pinyin: "xuéxiào", meaning: "trường học", type: "n" },
            { id: "h1_59", hanzi: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng", type: "n" },
            { id: "h1_60", hanzi: "家", pinyin: "jiā", meaning: "nhà", type: "n" },
            { id: "h1_61", hanzi: "房间", pinyin: "fángjiān", meaning: "phòng", type: "n" },
            { id: "h1_62", hanzi: "桌子", pinyin: "zhuōzi", meaning: "cái bàn", type: "n" },
            { id: "h1_63", hanzi: "椅子", pinyin: "yǐzi", meaning: "cái ghế", type: "n" },
            { id: "h1_64", hanzi: "杯子", pinyin: "bēizi", meaning: "cái cốc", type: "n" },
            { id: "h1_65", hanzi: "衣服", pinyin: "yīfu", meaning: "quần áo", type: "n" },
            { id: "h1_66", hanzi: "电视", pinyin: "diànshì", meaning: "ti vi", type: "n" },
            { id: "h1_67", hanzi: "电脑", pinyin: "diànnǎo", meaning: "máy tính", type: "n" },
            { id: "h1_68", hanzi: "电话", pinyin: "diànhuà", meaning: "điện thoại", type: "n" },
            { id: "h1_69", hanzi: "汽车", pinyin: "qìchē", meaning: "xe hơi", type: "n" },
            { id: "h1_70", hanzi: "飞机", pinyin: "fēijī", meaning: "máy bay", type: "n" },
            { id: "h1_71", hanzi: "出租车", pinyin: "chūzūchē", meaning: "xe taxi", type: "n" },
            { id: "h1_72", hanzi: "书", pinyin: "shū", meaning: "sách", type: "n" },
            { id: "h1_73", hanzi: "汉语", pinyin: "Hànyǔ", meaning: "tiếng Hán", type: "n" },
            { id: "h1_74", hanzi: "中文", pinyin: "Zhōngwén", meaning: "tiếng Trung", type: "n" },
            { id: "h1_75", hanzi: "英语", pinyin: "Yīngyǔ", meaning: "tiếng Anh", type: "n" },
            { id: "h1_76", hanzi: "点", pinyin: "diǎn", meaning: "giờ, điểm", type: "n" },
            { id: "h1_77", hanzi: "分钟", pinyin: "fēnzhōng", meaning: "phút", type: "n" },
            { id: "h1_78", hanzi: "星期", pinyin: "xīngqī", meaning: "tuần", type: "n" },
            { id: "h1_79", hanzi: "月", pinyin: "yuè", meaning: "tháng", type: "n" },
            { id: "h1_80", hanzi: "年", pinyin: "nián", meaning: "năm", type: "n" },
            { id: "h1_81", hanzi: "现在", pinyin: "xiànzài", meaning: "hiện tại, bây giờ", type: "n" },
            { id: "h1_82", hanzi: "时候", pinyin: "shíhou", meaning: "lúc, thời điểm", type: "n" },
            { id: "h1_83", hanzi: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng", type: "n" },
            { id: "h1_84", hanzi: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều", type: "n" },
            { id: "h1_85", hanzi: "晚上", pinyin: "wǎnshang", meaning: "buổi tối", type: "n" },
            { id: "h1_86", hanzi: "天气", pinyin: "tiānqì", meaning: "thời tiết", type: "n" },
            { id: "h1_87", hanzi: "这", pinyin: "zhè", meaning: "này", type: "pron" },
            { id: "h1_88", hanzi: "那", pinyin: "nà", meaning: "kia, đó", type: "pron" },
            { id: "h1_89", hanzi: "这里", pinyin: "zhèlǐ", meaning: "ở đây", type: "pron" },
            { id: "h1_90", hanzi: "那里", pinyin: "nàlǐ", meaning: "ở đó", type: "pron" },
            { id: "h1_91", hanzi: "哪", pinyin: "nǎ", meaning: "nào", type: "pron" },
            { id: "h1_92", hanzi: "哪里", pinyin: "nǎlǐ", meaning: "ở đâu", type: "pron" },
            { id: "h1_93", hanzi: "里", pinyin: "lǐ", meaning: "trong, bên trong", type: "n" },
            { id: "h1_94", hanzi: "上", pinyin: "shàng", meaning: "trên", type: "n" },
            { id: "h1_95", hanzi: "下", pinyin: "xià", meaning: "dưới", type: "n" },
            { id: "h1_96", hanzi: "前面", pinyin: "qiánmiàn", meaning: "phía trước", type: "n" },
            { id: "h1_97", hanzi: "后面", pinyin: "hòumiàn", meaning: "phía sau", type: "n" },
            { id: "h1_98", hanzi: "说", pinyin: "shuō", meaning: "nói", type: "v" },
            { id: "h1_99", hanzi: "读", pinyin: "dú", meaning: "đọc", type: "v" },
            { id: "h1_100", hanzi: "写", pinyin: "xiě", meaning: "viết", type: "v" },
            { id: "h1_101", hanzi: "学习", pinyin: "xuéxí", meaning: "học tập", type: "v" },
            { id: "h1_102", hanzi: "工作", pinyin: "gōngzuò", meaning: "làm việc", type: "v" },
            { id: "h1_103", hanzi: "睡觉", pinyin: "shuìjiào", meaning: "ngủ", type: "v" },
            { id: "h1_104", hanzi: "起床", pinyin: "qǐchuáng", meaning: "thức dậy", type: "v" },
            { id: "h1_105", hanzi: "做", pinyin: "zuò", meaning: "làm", type: "v" },
            { id: "h1_106", hanzi: "买", pinyin: "mǎi", meaning: "mua", type: "v" },
            { id: "h1_107", hanzi: "坐", pinyin: "zuò", meaning: "ngồi", type: "v" },
            { id: "h1_108", hanzi: "开", pinyin: "kāi", meaning: "mở, lái (xe)", type: "v" },
            { id: "h1_109", hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "gọi điện thoại", type: "v" },
            { id: "h1_110", hanzi: "高兴", pinyin: "gāoxìng", meaning: "vui vẻ", type: "adj" },
            { id: "h1_111", hanzi: "漂亮", pinyin: "piàoliang", meaning: "xinh đẹp", type: "adj" },
            { id: "h1_112", hanzi: "高", pinyin: "gāo", meaning: "cao", type: "adj" },
            { id: "h1_113", hanzi: "冷", pinyin: "lěng", meaning: "lạnh", type: "adj" },
            { id: "h1_114", hanzi: "热", pinyin: "rè", meaning: "nóng", type: "adj" },
            { id: "h1_115", hanzi: "新", pinyin: "xīn", meaning: "mới", type: "adj" },
            { id: "h1_116", hanzi: "忙", pinyin: "máng", meaning: "bận", type: "adj" },
            { id: "h1_117", hanzi: "累", pinyin: "lèi", meaning: "mệt", type: "adj" },
            { id: "h1_118", hanzi: "和", pinyin: "hé", meaning: "và", type: "conj" },
            { id: "h1_119", hanzi: "一起", pinyin: "yìqǐ", meaning: "cùng nhau", type: "adv" },
            { id: "h1_120", hanzi: "都", pinyin: "dōu", meaning: "đều", type: "adv" },
            { id: "h1_121", hanzi: "也", pinyin: "yě", meaning: "cũng", type: "adv" },
            { id: "h1_122", hanzi: "还", pinyin: "hái", meaning: "vẫn còn", type: "adv" },
            { id: "h1_123", hanzi: "再", pinyin: "zài", meaning: "lại (lần nữa)", type: "adv" },
            { id: "h1_124", hanzi: "就", pinyin: "jiù", meaning: "thì, liền", type: "adv" },
            { id: "h1_125", hanzi: "太", pinyin: "tài", meaning: "quá", type: "adv" },
            { id: "h1_126", hanzi: "非常", pinyin: "fēicháng", meaning: "vô cùng", type: "adv" },
            { id: "h1_127", hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "một chút", type: "m" },
            { id: "h1_128", hanzi: "到", pinyin: "dào", meaning: "đến", type: "v" },
            { id: "h1_129", hanzi: "给", pinyin: "gěi", meaning: "cho", type: "v" },
            { id: "h1_130", hanzi: "谁", pinyin: "shéi", meaning: "ai", type: "pron" },
            { id: "h1_131", hanzi: "怎么", pinyin: "zěnme", meaning: "thế nào, sao", type: "pron" },
            { id: "h1_132", hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "thế nào (hỏi ý kiến)", type: "pron" },
            { id: "h1_133", hanzi: "为什么", pinyin: "wèishénme", meaning: "tại sao", type: "pron" },
            { id: "h1_134", hanzi: "几", pinyin: "jǐ", meaning: "mấy", type: "pron" },
            { id: "h1_135", hanzi: "多少", pinyin: "duōshao", meaning: "bao nhiêu", type: "pron" },
            { id: "h1_136", hanzi: "了", pinyin: "le", meaning: "(trợ từ chỉ sự hoàn thành)", type: "part" },
            { id: "h1_137", hanzi: "的", pinyin: "de", meaning: "(trợ từ sở hữu, của)", type: "part" },
            { id: "h1_138", hanzi: "呢", pinyin: "ne", meaning: "(trợ từ nghi vấn)", type: "part" },
            { id: "h1_139", hanzi: "吧", pinyin: "ba", meaning: "(trợ từ đề nghị, rủ rê)", type: "part" }
        ],
        grammar: [
            {
                id: "g1_1",
                title: "Câu hỏi với 吗 (ma)",
                description: "Thêm '吗' vào cuối câu trần thuật để tạo thành câu hỏi Có/Không.",
                example: { hanzi: "你好吗？", pinyin: "Nǐ hǎo ma?", meaning: "Bạn có khỏe không?" }
            },
            {
                id: "g1_2",
                title: "Phủ định với 不 (bù)",
                description: "Đặt '不' trước động từ hoặc tính từ để biểu thị sự phủ định.",
                example: { hanzi: "我不吃苹果。", pinyin: "Wǒ bù chī píngguǒ.", meaning: "Tôi không ăn táo." }
            },
            {
                id: "g1_3",
                title: "Câu chữ 是 (shì)",
                description: "Dùng để nối chủ ngữ và vị ngữ danh từ, mang ý nghĩa 'A là B'.",
                example: { hanzi: "他是老师。", pinyin: "Tā shì lǎoshī.", meaning: "Anh ấy là giáo viên." }
            },
            {
                id: "g1_4",
                title: "Trạng từ 很 (hěn)",
                description: "Dùng trước tính từ để chỉ mức độ cao (rất). Thường dùng trong câu khẳng định với tính từ.",
                example: { hanzi: "我很好。", pinyin: "Wǒ hěn hǎo.", meaning: "Tôi rất khỏe." }
            },
            {
                id: "g1_5",
                title: "Câu có động từ 有 (yǒu)",
                description: "Biểu thị sự sở hữu hoặc tồn tại: Chủ ngữ + 有 + tân ngữ.",
                example: { hanzi: "我有一只猫。", pinyin: "Wǒ yǒu yì zhī māo.", meaning: "Tôi có một con mèo." }
            },
            {
                id: "g1_6",
                title: "Lượng từ (量词)",
                description: "Giữa số từ và danh từ thường phải có lượng từ phù hợp, ví dụ 个, 只, 本.",
                example: { hanzi: "一个人，一只狗，一本书", pinyin: "yí gè rén, yì zhī gǒu, yì běn shū", meaning: "một người, một con chó, một quyển sách" }
            },
            {
                id: "g1_7",
                title: "Câu hỏi chính phản (V/A-不-V/A)",
                description: "Lặp lại động từ hoặc tính từ với 不 ở giữa để tạo câu hỏi, tương đương câu hỏi với 吗.",
                example: { hanzi: "你去不去？", pinyin: "Nǐ qù bú qù?", meaning: "Bạn có đi không?" }
            }
        ]
    },
    hsk2: {
        vocabulary: [
            { id: "h2_1", hanzi: "因为", pinyin: "yīnwèi", meaning: "bởi vì", type: "conj" },
            { id: "h2_2", hanzi: "所以", pinyin: "suǒyǐ", meaning: "cho nên", type: "conj" },
            { id: "h2_3", hanzi: "但是", pinyin: "dànshì", meaning: "nhưng mà", type: "conj" },
            { id: "h2_4", hanzi: "觉得", pinyin: "juéde", meaning: "cảm thấy", type: "v" },
            { id: "h2_5", hanzi: "比", pinyin: "bǐ", meaning: "so với (so sánh)", type: "prep" },
            { id: "h2_6", hanzi: "可能", pinyin: "kěnéng", meaning: "có thể", type: "adv" },
            { id: "h2_7", hanzi: "希望", pinyin: "xīwàng", meaning: "hy vọng", type: "v" },
            { id: "h2_8", hanzi: "问题", pinyin: "wèntí", meaning: "vấn đề, câu hỏi", type: "n" },
            { id: "h2_9", hanzi: "意思", pinyin: "yìsi", meaning: "ý nghĩa", type: "n" },
            { id: "h2_10", hanzi: "可以", pinyin: "kěyǐ", meaning: "có thể, được phép", type: "v" },
            { id: "h2_11", hanzi: "最", pinyin: "zuì", meaning: "nhất", type: "adv" },
            { id: "h2_12", hanzi: "知道", pinyin: "zhīdào", meaning: "biết", type: "v" },
            { id: "h2_13", hanzi: "穿", pinyin: "chuān", meaning: "mặc (quần áo)", type: "v" },
            { id: "h2_14", hanzi: "便宜", pinyin: "piányi", meaning: "rẻ", type: "adj" },
            { id: "h2_15", hanzi: "贵", pinyin: "guì", meaning: "đắt", type: "adj" },
            { id: "h2_16", hanzi: "旁边", pinyin: "pángbiān", meaning: "bên cạnh", type: "n" },
            { id: "h2_17", hanzi: "远", pinyin: "yuǎn", meaning: "xa", type: "adj" },
            { id: "h2_18", hanzi: "近", pinyin: "jìn", meaning: "gần", type: "adj" },
            { id: "h2_19", hanzi: "快", pinyin: "kuài", meaning: "nhanh", type: "adj" },
            { id: "h2_20", hanzi: "慢", pinyin: "màn", meaning: "chậm", type: "adj" },
            { id: "h2_21", hanzi: "一样", pinyin: "yíyàng", meaning: "giống nhau", type: "adj" },
            { id: "h2_22", hanzi: "一定", pinyin: "yídìng", meaning: "nhất định", type: "adv" },
            { id: "h2_23", hanzi: "一般", pinyin: "yìbān", meaning: "thông thường", type: "adj" },
            { id: "h2_24", hanzi: "一共", pinyin: "yígòng", meaning: "tổng cộng", type: "adv" },
            { id: "h2_25", hanzi: "关心", pinyin: "guānxīn", meaning: "quan tâm", type: "v" },
            { id: "h2_26", hanzi: "关于", pinyin: "guānyú", meaning: "về, liên quan đến", type: "prep" },
            { id: "h2_27", hanzi: "参加", pinyin: "cānjiā", meaning: "tham gia", type: "v" },
            { id: "h2_28", hanzi: "又", pinyin: "yòu", meaning: "lại (việc đã xảy ra)", type: "adv" },
            { id: "h2_29", hanzi: "只", pinyin: "zhǐ", meaning: "chỉ", type: "adv" },
            { id: "h2_30", hanzi: "才", pinyin: "cái", meaning: "mới, mãi mới", type: "adv" },
            { id: "h2_31", hanzi: "已经", pinyin: "yǐjīng", meaning: "đã rồi", type: "adv" },
            { id: "h2_32", hanzi: "一会儿", pinyin: "yíhuìr", meaning: "một lát", type: "n" },
            { id: "h2_33", hanzi: "会", pinyin: "huì", meaning: "biết, sẽ", type: "v" },
            { id: "h2_34", hanzi: "能", pinyin: "néng", meaning: "có thể (năng lực)", type: "aux" },
            { id: "h2_35", hanzi: "打算", pinyin: "dǎsuàn", meaning: "dự định", type: "v" },
            { id: "h2_36", hanzi: "决定", pinyin: "juédìng", meaning: "quyết định", type: "v" },
            { id: "h2_37", hanzi: "检查", pinyin: "jiǎnchá", meaning: "kiểm tra", type: "v" },
            { id: "h2_38", hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "thư viện", type: "n" },
            { id: "h2_39", hanzi: "医院", pinyin: "yīyuàn", meaning: "bệnh viện", type: "n" },
            { id: "h2_40", hanzi: "银行", pinyin: "yínháng", meaning: "ngân hàng", type: "n" },
            { id: "h2_41", hanzi: "机场", pinyin: "jīchǎng", meaning: "sân bay", type: "n" },
            { id: "h2_42", hanzi: "公司", pinyin: "gōngsī", meaning: "công ty", type: "n" },
            { id: "h2_43", hanzi: "经理", pinyin: "jīnglǐ", meaning: "giám đốc", type: "n" },
            { id: "h2_44", hanzi: "同事", pinyin: "tóngshì", meaning: "đồng nghiệp", type: "n" },
            { id: "h2_45", hanzi: "邻居", pinyin: "línjū", meaning: "hàng xóm", type: "n" },
            { id: "h2_46", hanzi: "帮助", pinyin: "bāngzhù", meaning: "giúp đỡ", type: "v" },
            { id: "h2_47", hanzi: "提高", pinyin: "tígāo", meaning: "nâng cao", type: "v" },
            { id: "h2_48", hanzi: "影响", pinyin: "yǐngxiǎng", meaning: "ảnh hưởng", type: "v" },
            { id: "h2_49", hanzi: "复习", pinyin: "fùxí", meaning: "ôn tập", type: "v" },
            { id: "h2_50", hanzi: "练习", pinyin: "liànxí", meaning: "luyện tập", type: "v" },
            { id: "h2_51", hanzi: "考试", pinyin: "kǎoshì", meaning: "thi cử", type: "v" },
            { id: "h2_52", hanzi: "成绩", pinyin: "chéngjì", meaning: "thành tích", type: "n" },
            { id: "h2_53", hanzi: "借", pinyin: "jiè", meaning: "mượn", type: "v" },
            { id: "h2_54", hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "thư điện tử (email)", type: "n" },
            { id: "h2_55", hanzi: "上网", pinyin: "shàngwǎng", meaning: "lên mạng", type: "v" },
            { id: "h2_56", hanzi: "迟到", pinyin: "chídào", meaning: "đến muộn", type: "v" },
            { id: "h2_57", hanzi: "突然", pinyin: "tūrán", meaning: "đột nhiên", type: "adv" },
            { id: "h2_58", hanzi: "一切", pinyin: "yíqiè", meaning: "tất cả", type: "pron" },
            { id: "h2_59", hanzi: "而", pinyin: "ér", meaning: "mà (liên từ)", type: "conj" },
            { id: "h2_60", hanzi: "甚至", pinyin: "shènzhì", meaning: "thậm chí", type: "adv" }
        ],
        grammar: [
            {
                id: "g2_1",
                title: "Cấu trúc 因为...所以...",
                description: "Dùng để biểu thị quan hệ nguyên nhân - kết quả (bởi vì... cho nên...).",
                example: { hanzi: "因为下雨，所以我不去。", pinyin: "Yīnwèi xiàyǔ, suǒyǐ wǒ bù qù.", meaning: "Bởi vì trời mưa, cho nên tôi không đi." }
            },
            {
                id: "g2_2",
                title: "Câu so sánh với 比 (bǐ)",
                description: "A + 比 + B + tính từ: A tính từ hơn B.",
                example: { hanzi: "哥哥比我高。", pinyin: "Gēge bǐ wǒ gāo.", meaning: "Anh trai cao hơn tôi." }
            },
            {
                id: "g2_3",
                title: "Động từ năng nguyện 可以 (kěyǐ)",
                description: "Biểu thị sự cho phép hoặc khả năng.",
                example: { hanzi: "我可以进来吗？", pinyin: "Wǒ kěyǐ jìnlái ma?", meaning: "Tôi có thể vào không?" }
            },
            {
                id: "g2_4",
                title: "Bổ ngữ trình độ với 得 (de)",
                description: "Động từ/tính từ + 得 + bổ ngữ, dùng để miêu tả mức độ hoặc trạng thái.",
                example: { hanzi: "他跑得很快。", pinyin: "Tā pǎo de hěn kuài.", meaning: "Anh ấy chạy rất nhanh." }
            },
            {
                id: "g2_5",
                title: "Trợ động từ 要/想 chỉ ý muốn",
                description: "要/想 + động từ, biểu thị mong muốn hoặc dự định làm gì.",
                example: { hanzi: "我想去中国。", pinyin: "Wǒ xiǎng qù Zhōngguó.", meaning: "Tôi muốn đi Trung Quốc." }
            }
        ]
    },
    hsk3: {
        vocabulary: [
            { id: "h3_1", hanzi: "虽然", pinyin: "suīrán", meaning: "mặc dù", type: "conj" },
            { id: "h3_2", hanzi: "一直", pinyin: "yīzhí", meaning: "luôn luôn, suốt", type: "adv" },
            { id: "h3_3", hanzi: "而且", pinyin: "érqiě", meaning: "mà còn, hơn nữa", type: "conj" },
            { id: "h3_4", hanzi: "发现", pinyin: "fāxiàn", meaning: "phát hiện", type: "v" },
            { id: "h3_5", hanzi: "离开", pinyin: "líkāi", meaning: "rời khỏi", type: "v" },
            { id: "h3_6", hanzi: "需要", pinyin: "xūyào", meaning: "cần thiết", type: "v" },
            { id: "h3_7", hanzi: "终于", pinyin: "zhōngyú", meaning: "cuối cùng", type: "adv" },
            { id: "h3_8", hanzi: "愿意", pinyin: "yuànyì", meaning: "bằng lòng, muốn", type: "v" },
            { id: "h3_9", hanzi: "或者", pinyin: "huòzhě", meaning: "hoặc là", type: "conj" },
            { id: "h3_10", hanzi: "还是", pinyin: "háishì", meaning: "hay là", type: "conj" },
            { id: "h3_11", hanzi: "适合", pinyin: "shìhé", meaning: "phù hợp", type: "v" },
            { id: "h3_12", hanzi: "尊重", pinyin: "zūnzhòng", meaning: "tôn trọng", type: "v" },
            { id: "h3_13", hanzi: "讨论", pinyin: "tǎolùn", meaning: "thảo luận", type: "v" },
            { id: "h3_14", hanzi: "计划", pinyin: "jìhuà", meaning: "kế hoạch", type: "n" },
            { id: "h3_15", hanzi: "介绍", pinyin: "jièshào", meaning: "giới thiệu", type: "v" },
            { id: "h3_16", hanzi: "环境", pinyin: "huánjìng", meaning: "môi trường", type: "n" },
            { id: "h3_17", hanzi: "社会", pinyin: "shèhuì", meaning: "xã hội", type: "n" },
            { id: "h3_18", hanzi: "经济", pinyin: "jīngjì", meaning: "kinh tế", type: "n" },
            { id: "h3_19", hanzi: "文化", pinyin: "wénhuà", meaning: "văn hóa", type: "n" },
            { id: "h3_20", hanzi: "历史", pinyin: "lìshǐ", meaning: "lịch sử", type: "n" },
            { id: "h3_21", hanzi: "态度", pinyin: "tàidù", meaning: "thái độ", type: "n" },
            { id: "h3_22", hanzi: "性格", pinyin: "xìnggé", meaning: "tính cách", type: "n" },
            { id: "h3_23", hanzi: "压力", pinyin: "yālì", meaning: "áp lực", type: "n" },
            { id: "h3_24", hanzi: "机会", pinyin: "jīhuì", meaning: "cơ hội", type: "n" },
            { id: "h3_25", hanzi: "经验", pinyin: "jīngyàn", meaning: "kinh nghiệm", type: "n" },
            { id: "h3_26", hanzi: "目的", pinyin: "mùdì", meaning: "mục đích", type: "n" },
            { id: "h3_27", hanzi: "结果", pinyin: "jiéguǒ", meaning: "kết quả", type: "n" },
            { id: "h3_28", hanzi: "原因", pinyin: "yuányīn", meaning: "nguyên nhân", type: "n" },
            { id: "h3_29", hanzi: "解决", pinyin: "jiějué", meaning: "giải quyết", type: "v" },
            { id: "h3_30", hanzi: "提供", pinyin: "tígōng", meaning: "cung cấp", type: "v" },
            { id: "h3_31", hanzi: "表示", pinyin: "biǎoshì", meaning: "biểu thị", type: "v" },
            { id: "h3_32", hanzi: "建议", pinyin: "jiànyì", meaning: "đề nghị", type: "v" },
            { id: "h3_33", hanzi: "支持", pinyin: "zhīchí", meaning: "ủng hộ", type: "v" },
            { id: "h3_34", hanzi: "拒绝", pinyin: "jùjué", meaning: "từ chối", type: "v" },
            { id: "h3_35", hanzi: "允许", pinyin: "yǔnxǔ", meaning: "cho phép", type: "v" },
            { id: "h3_36", hanzi: "值得", pinyin: "zhíde", meaning: "đáng giá", type: "v" },
            { id: "h3_37", hanzi: "逐渐", pinyin: "zhújiàn", meaning: "dần dần", type: "adv" },
            { id: "h3_38", hanzi: "尤其", pinyin: "yóuqí", meaning: "đặc biệt là", type: "adv" },
            { id: "h3_39", hanzi: "反而", pinyin: "fǎn'ér", meaning: "ngược lại", type: "adv" },
            { id: "h3_40", hanzi: "明显", pinyin: "míngxiǎn", meaning: "rõ ràng", type: "adj" }
        ],
        grammar: [
            {
                id: "g3_1",
                title: "Cấu trúc 虽然...但是...",
                description: "Dùng để biểu thị quan hệ nhượng bộ (mặc dù... nhưng...).",
                example: { hanzi: "虽然很累，但是很高兴。", pinyin: "Suīrán hěn lèi, dànshì hěn gāoxìng.", meaning: "Mặc dù rất mệt, nhưng rất vui." }
            },
            {
                id: "g3_2",
                title: "Phân biệt 或者 và 还是",
                description: "或者 dùng trong câu kể (hoặc là). 还是 dùng trong câu hỏi (hay là).",
                example: { hanzi: "你喝茶还是喝咖啡？", pinyin: "Nǐ hē chá háishì hē kāfēi?", meaning: "Bạn uống trà hay uống cà phê?" }
            },
            {
                id: "g3_3",
                title: "Câu chữ 把 (bǎ)",
                description: "Chủ ngữ + 把 + tân ngữ + động từ + thành phần khác, nhấn mạnh sự xử lý/tác động lên đối tượng.",
                example: { hanzi: "我把书放在桌子上。", pinyin: "Wǒ bǎ shū fàng zài zhuōzi shàng.", meaning: "Tôi để sách lên bàn." }
            },
            {
                id: "g3_4",
                title: "Câu bị động với 被 (bèi)",
                description: "Chủ ngữ (bị tác động) + 被 + (chủ thể gây tác động) + động từ, dùng để nhấn mạnh đối tượng chịu ảnh hưởng.",
                example: { hanzi: "杯子被我打破了。", pinyin: "Bēizi bèi wǒ dǎ pò le.", meaning: "Cái cốc bị tôi làm vỡ." }
            }
        ]
    },
    hsk4: {
        vocabulary: [
            { id: "h4_1", hanzi: "不管", pinyin: "bùguǎn", meaning: "cho dù, bất kể", type: "conj" },
            { id: "h4_2", hanzi: "否则", pinyin: "fǒuzé", meaning: "nếu không thì", type: "conj" },
            { id: "h4_3", hanzi: "随着", pinyin: "suízhe", meaning: "cùng với", type: "prep" },
            { id: "h4_4", hanzi: "即使", pinyin: "jíshǐ", meaning: "cho dù, ngay cả khi", type: "conj" },
            { id: "h4_5", hanzi: "由于", pinyin: "yóuyú", meaning: "do, bởi vì", type: "prep" },
            { id: "h4_6", hanzi: "原来", pinyin: "yuánlái", meaning: "vốn dĩ, hóa ra", type: "adv" },
            { id: "h4_7", hanzi: "难道", pinyin: "nándào", meaning: "lẽ nào", type: "adv" },
            { id: "h4_8", hanzi: "偶尔", pinyin: "ǒu'ěr", meaning: "thỉnh thoảng", type: "adv" },
            { id: "h4_9", hanzi: "竟然", pinyin: "jìngrán", meaning: "mà lại, vậy mà", type: "adv" },
            { id: "h4_10", hanzi: "肯定", pinyin: "kěndìng", meaning: "chắc chắn", type: "adv" },
            { id: "h4_11", hanzi: "承认", pinyin: "chéngrèn", meaning: "thừa nhận", type: "v" },
            { id: "h4_12", hanzi: "承担", pinyin: "chéngdān", meaning: "đảm nhận, gánh vác", type: "v" },
            { id: "h4_13", hanzi: "采取", pinyin: "cǎiqǔ", meaning: "áp dụng, tiến hành", type: "v" },
            { id: "h4_14", hanzi: "促进", pinyin: "cùjìn", meaning: "thúc đẩy", type: "v" },
            { id: "h4_15", hanzi: "从而", pinyin: "cóng'ér", meaning: "từ đó, do đó", type: "conj" },
            { id: "h4_16", hanzi: "导致", pinyin: "dǎozhì", meaning: "dẫn đến", type: "v" },
            { id: "h4_17", hanzi: "反映", pinyin: "fǎnyìng", meaning: "phản ánh", type: "v" },
            { id: "h4_18", hanzi: "分析", pinyin: "fēnxī", meaning: "phân tích", type: "v" },
            { id: "h4_19", hanzi: "观察", pinyin: "guānchá", meaning: "quan sát", type: "v" },
            { id: "h4_20", hanzi: "具备", pinyin: "jùbèi", meaning: "có sẵn, hội đủ", type: "v" },
            { id: "h4_21", hanzi: "具体", pinyin: "jùtǐ", meaning: "cụ thể", type: "adj" },
            { id: "h4_22", hanzi: "强调", pinyin: "qiángdiào", meaning: "nhấn mạnh", type: "v" },
            { id: "h4_23", hanzi: "缺乏", pinyin: "quēfá", meaning: "thiếu", type: "v" },
            { id: "h4_24", hanzi: "设计", pinyin: "shèjì", meaning: "thiết kế", type: "v" },
            { id: "h4_25", hanzi: "实现", pinyin: "shíxiàn", meaning: "thực hiện", type: "v" },
            { id: "h4_26", hanzi: "现象", pinyin: "xiànxiàng", meaning: "hiện tượng", type: "n" },
            { id: "h4_27", hanzi: "依靠", pinyin: "yīkào", meaning: "dựa vào", type: "v" },
            { id: "h4_28", hanzi: "因素", pinyin: "yīnsù", meaning: "nhân tố", type: "n" },
            { id: "h4_29", hanzi: "逐步", pinyin: "zhúbù", meaning: "từng bước", type: "adv" },
            { id: "h4_30", hanzi: "综合", pinyin: "zōnghé", meaning: "tổng hợp", type: "v" },
            { id: "h4_31", hanzi: "追求", pinyin: "zhuīqiú", meaning: "theo đuổi", type: "v" },
            { id: "h4_32", hanzi: "状态", pinyin: "zhuàngtài", meaning: "trạng thái", type: "n" },
            { id: "h4_33", hanzi: "责任", pinyin: "zérèn", meaning: "trách nhiệm", type: "n" },
            { id: "h4_34", hanzi: "战略", pinyin: "zhànlüè", meaning: "chiến lược", type: "n" },
            { id: "h4_35", hanzi: "争议", pinyin: "zhēngyì", meaning: "tranh cãi", type: "n" }
        ],
        grammar: [
            {
                id: "g4_1",
                title: "Cấu trúc 不管...都/也...",
                description: "Cho dù... đều/cũng...",
                example: { hanzi: "不管多累，他都坚持锻炼。", pinyin: "Bùguǎn duō lèi, tā dōu jiānchí duànliàn.", meaning: "Cho dù rất mệt, anh ấy đều kiên trì tập thể dục." }
            },
            {
                id: "g4_2",
                title: "Cấu trúc 即使...也...",
                description: "Ngay cả khi... cũng... (chỉ sự việc giả định).",
                example: { hanzi: "即使下雨，我也要去。", pinyin: "Jíshǐ xiàyǔ, wǒ yě yào qù.", meaning: "Ngay cả khi trời mưa, tôi cũng phải đi." }
            },
            {
                id: "g4_3",
                title: "Cấu trúc 除了...以外...",
                description: "Ngoài... ra... (thường đi kèm 还/也 để bổ sung thêm ý).",
                example: { hanzi: "除了英语以外，他还会说法语。", pinyin: "Chúle Yīngyǔ yǐwài, tā hái huì shuō Fǎyǔ.", meaning: "Ngoài tiếng Anh ra, anh ấy còn biết nói tiếng Pháp." }
            }
        ]
    },
    hsk5: {
        vocabulary: [
            { id: "h5_1", hanzi: "果然", pinyin: "guǒrán", meaning: "quả nhiên", type: "adv" },
            { id: "h5_2", hanzi: "似乎", pinyin: "sìhū", meaning: "dường như", type: "adv" },
            { id: "h5_3", hanzi: "显然", pinyin: "xiǎnrán", meaning: "hiển nhiên", type: "adv" },
            { id: "h5_4", hanzi: "曾经", pinyin: "céngjīng", meaning: "đã từng", type: "adv" },
            { id: "h5_5", hanzi: "到底", pinyin: "dàodǐ", meaning: "rốt cuộc", type: "adv" },
            { id: "h5_6", hanzi: "毕竟", pinyin: "bìjìng", meaning: "suy cho cùng", type: "adv" },
            { id: "h5_7", hanzi: "稍微", pinyin: "shāowēi", meaning: "hơi, một chút", type: "adv" },
            { id: "h5_8", hanzi: "难怪", pinyin: "nánguài", meaning: "thảo nào", type: "adv" },
            { id: "h5_9", hanzi: "万一", pinyin: "wànyī", meaning: "nhỡ đâu", type: "conj" },
            { id: "h5_10", hanzi: "究竟", pinyin: "jiūjìng", meaning: "rốt cuộc, cuối cùng", type: "adv" },
            { id: "h5_11", hanzi: "权利", pinyin: "quánlì", meaning: "quyền lợi", type: "n" },
            { id: "h5_12", hanzi: "权威", pinyin: "quánwēi", meaning: "quyền uy", type: "n" },
            { id: "h5_13", hanzi: "摆脱", pinyin: "bǎituō", meaning: "thoát khỏi", type: "v" },
            { id: "h5_14", hanzi: "表达", pinyin: "biǎodá", meaning: "diễn đạt", type: "v" },
            { id: "h5_15", hanzi: "补充", pinyin: "bǔchōng", meaning: "bổ sung", type: "v" },
            { id: "h5_16", hanzi: "采纳", pinyin: "cǎinà", meaning: "tiếp thu, chấp nhận", type: "v" },
            { id: "h5_17", hanzi: "衡量", pinyin: "héngliáng", meaning: "cân nhắc, đánh giá", type: "v" },
            { id: "h5_18", hanzi: "忽视", pinyin: "hūshì", meaning: "xem nhẹ, bỏ qua", type: "v" },
            { id: "h5_19", hanzi: "简直", pinyin: "jiǎnzhí", meaning: "đơn giản là, quả thực", type: "adv" },
            { id: "h5_20", hanzi: "局限", pinyin: "júxiàn", meaning: "hạn chế, giới hạn", type: "v" },
            { id: "h5_21", hanzi: "履行", pinyin: "lǚxíng", meaning: "thực hiện (nghĩa vụ)", type: "v" },
            { id: "h5_22", hanzi: "迫切", pinyin: "pòqiè", meaning: "cấp bách", type: "adj" },
            { id: "h5_23", hanzi: "契机", pinyin: "qìjī", meaning: "cơ hội, bước ngoặt", type: "n" },
            { id: "h5_24", hanzi: "倾向", pinyin: "qīngxiàng", meaning: "khuynh hướng", type: "n" },
            { id: "h5_25", hanzi: "妥协", pinyin: "tuǒxié", meaning: "thỏa hiệp", type: "v" },
            { id: "h5_26", hanzi: "维持", pinyin: "wéichí", meaning: "duy trì", type: "v" },
            { id: "h5_27", hanzi: "显著", pinyin: "xiǎnzhù", meaning: "rõ rệt", type: "adj" },
            { id: "h5_28", hanzi: "隐藏", pinyin: "yǐncáng", meaning: "ẩn giấu", type: "v" },
            { id: "h5_29", hanzi: "涉及", pinyin: "shèjí", meaning: "liên quan đến", type: "v" },
            { id: "h5_30", hanzi: "侧重", pinyin: "cèzhòng", meaning: "chú trọng", type: "v" }
        ],
        grammar: [
            {
                id: "g5_1",
                title: "Từ vựng 到底 (rốt cuộc)",
                description: "Dùng trong câu hỏi để nhấn mạnh ý muốn tìm hiểu đến cùng.",
                example: { hanzi: "你到底去不去？", pinyin: "Nǐ dàodǐ qù bú qù?", meaning: "Rốt cuộc bạn có đi không?" }
            },
            {
                id: "g5_2",
                title: "Cấu trúc 难怪...原来...",
                description: "Thảo nào... hóa ra...",
                example: { hanzi: "难怪他没来，原来他生病了。", pinyin: "Nánguài tā méi lái, yuánlái tā shēngbìng le.", meaning: "Thảo nào anh ấy không đến, hóa ra anh ấy bị ốm." }
            },
            {
                id: "g5_3",
                title: "Cấu trúc 不仅...而且...",
                description: "Không những... mà còn... (dùng để liệt kê, tăng tiến ý nghĩa).",
                example: { hanzi: "他不仅聪明，而且很努力。", pinyin: "Tā bùjǐn cōngming, érqiě hěn nǔlì.", meaning: "Anh ấy không những thông minh mà còn rất chăm chỉ." }
            }
        ]
    },
    hsk6: {
        vocabulary: [
            { id: "h6_1", hanzi: "哪怕", pinyin: "nǎpà", meaning: "ngay cả khi", type: "conj" },
            { id: "h6_2", hanzi: "何况", pinyin: "hékuàng", meaning: "huống hồ", type: "conj" },
            { id: "h6_3", hanzi: "与其", pinyin: "yǔqí", meaning: "thà rằng", type: "conj" },
            { id: "h6_4", hanzi: "宁可", pinyin: "nìngkě", meaning: "thà", type: "conj" },
            { id: "h6_5", hanzi: "以便", pinyin: "yǐbiàn", meaning: "để, nhằm", type: "conj" },
            { id: "h6_6", hanzi: "进而", pinyin: "jìn'ér", meaning: "hơn nữa, tiến tới", type: "conj" },
            { id: "h6_7", hanzi: "总之", pinyin: "zǒngzhī", meaning: "tóm lại", type: "conj" },
            { id: "h6_8", hanzi: "鉴于", pinyin: "jiànyú", meaning: "xét thấy, do", type: "prep" },
            { id: "h6_9", hanzi: "之际", pinyin: "zhījì", meaning: "vào lúc, trong khi", type: "n" },
            { id: "h6_10", hanzi: "固然", pinyin: "gùrán", meaning: "tuy rằng... nhưng...", type: "conj" },
            { id: "h6_11", hanzi: "剖析", pinyin: "pōuxī", meaning: "phân tích sâu, mổ xẻ", type: "v" },
            { id: "h6_12", hanzi: "蕴含", pinyin: "yùnhán", meaning: "chứa đựng, hàm chứa", type: "v" },
            { id: "h6_13", hanzi: "渗透", pinyin: "shèntòu", meaning: "thấm nhuần, thẩm thấu", type: "v" },
            { id: "h6_14", hanzi: "弘扬", pinyin: "hóngyáng", meaning: "phát huy, phát dương", type: "v" },
            { id: "h6_15", hanzi: "涣散", pinyin: "huànsàn", meaning: "rời rạc, lỏng lẻo", type: "adj" },
            { id: "h6_16", hanzi: "遏制", pinyin: "èzhì", meaning: "kiềm chế, ngăn chặn", type: "v" },
            { id: "h6_17", hanzi: "权衡", pinyin: "quánhéng", meaning: "cân nhắc", type: "v" },
            { id: "h6_18", hanzi: "汲取", pinyin: "jíqǔ", meaning: "hấp thu, rút ra (kinh nghiệm)", type: "v" },
            { id: "h6_19", hanzi: "蓬勃", pinyin: "péngbó", meaning: "mạnh mẽ, sôi nổi", type: "adj" },
            { id: "h6_20", hanzi: "匮乏", pinyin: "kuìfá", meaning: "thiếu thốn", type: "adj" },
            { id: "h6_21", hanzi: "恪守", pinyin: "kèshǒu", meaning: "tuân thủ nghiêm ngặt", type: "v" },
            { id: "h6_22", hanzi: "迄今", pinyin: "qìjīn", meaning: "cho đến nay", type: "adv" },
            { id: "h6_23", hanzi: "亘古", pinyin: "gèngǔ", meaning: "từ xưa đến nay", type: "adv" },
            { id: "h6_24", hanzi: "缜密", pinyin: "zhěnmì", meaning: "tỉ mỉ, chặt chẽ", type: "adj" },
            { id: "h6_25", hanzi: "卓越", pinyin: "zhuóyuè", meaning: "xuất sắc", type: "adj" },
            { id: "h6_26", hanzi: "韧性", pinyin: "rènxìng", meaning: "tính bền bỉ, dẻo dai", type: "n" },
            { id: "h6_27", hanzi: "底蕴", pinyin: "dǐyùn", meaning: "nội hàm, chiều sâu", type: "n" },
            { id: "h6_28", hanzi: "演绎", pinyin: "yǎnyì", meaning: "diễn dịch, suy diễn", type: "v" },
            { id: "h6_29", hanzi: "契合", pinyin: "qìhé", meaning: "phù hợp, ăn khớp", type: "v" },
            { id: "h6_30", hanzi: "昭示", pinyin: "zhāoshì", meaning: "cho thấy rõ, biểu thị", type: "v" }
        ],
        grammar: [
            {
                id: "g6_1",
                title: "Cấu trúc 与其...不如...",
                description: "Thà... còn hơn... (lựa chọn phương án tốt hơn).",
                example: { hanzi: "与其抱怨，不如行动。", pinyin: "Yǔqí bàoyuàn, bùrú xíngdòng.", meaning: "Thà hành động còn hơn là phàn nàn." }
            },
            {
                id: "g6_2",
                title: "Cấu trúc 宁可...也不...",
                description: "Thà (chấp nhận cái xấu)... cũng không (chấp nhận cái tệ hơn).",
                example: { hanzi: "他宁可不吃饭，也不吃药。", pinyin: "Tā nìngkě bù chī fàn, yě bù chī yào.", meaning: "Anh ấy thà không ăn cơm, cũng không uống thuốc." }
            },
            {
                id: "g6_3",
                title: "Cấu trúc 之所以...是因为...",
                description: "Sở dĩ (có kết quả này)... là vì (nguyên nhân)... - nhấn mạnh nguyên nhân, thường đặt sau khi nêu kết quả.",
                example: { hanzi: "他之所以成功，是因为他坚持不懈。", pinyin: "Tā zhī suǒyǐ chénggōng, shì yīnwèi tā jiānchí bú xiè.", meaning: "Sở dĩ anh ấy thành công là vì anh ấy kiên trì không ngừng." }
            }
        ]
    }
};
